//
// Translated by CS2J (http://www.cs2j.com): 2/15/2016 5:58:01 PM
//

package OpenDentBusiness.Crud;

import CS2JNet.System.StringSupport;
import OpenDentBusiness.Db;
import OpenDentBusiness.DbHelper;
import OpenDentBusiness.DrugManufacturer;
import OpenDentBusiness.PIn;
import OpenDentBusiness.POut;
import OpenDentBusiness.PrefC;
import OpenDentBusiness.RemotingClient;
import OpenDentBusiness.RemotingRole;
import OpenDentBusiness.ReplicationServers;

//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
public class DrugManufacturerCrud   
{
    /**
    * Gets one DrugManufacturer object from the database using the primary key.  Returns null if not found.
    */
    public static DrugManufacturer selectOne(long drugManufacturerNum) throws Exception {
        String command = "SELECT * FROM drugmanufacturer " + "WHERE DrugManufacturerNum = " + POut.long(drugManufacturerNum);
        List<DrugManufacturer> list = tableToList(Db.getTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets one DrugManufacturer object from the database using a query.
    */
    public static DrugManufacturer selectOne(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<DrugManufacturer> list = tableToList(Db.getTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets a list of DrugManufacturer objects from the database using a query.
    */
    public static List<DrugManufacturer> selectMany(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<DrugManufacturer> list = tableToList(Db.getTable(command));
        return list;
    }

    /**
    * Converts a DataTable to a list of objects.
    */
    public static List<DrugManufacturer> tableToList(DataTable table) throws Exception {
        List<DrugManufacturer> retVal = new List<DrugManufacturer>();
        DrugManufacturer drugManufacturer;
        for (int i = 0;i < table.Rows.Count;i++)
        {
            drugManufacturer = new DrugManufacturer();
            drugManufacturer.DrugManufacturerNum = PIn.Long(table.Rows[i]["DrugManufacturerNum"].ToString());
            drugManufacturer.ManufacturerName = PIn.String(table.Rows[i]["ManufacturerName"].ToString());
            drugManufacturer.ManufacturerCode = PIn.String(table.Rows[i]["ManufacturerCode"].ToString());
            retVal.Add(drugManufacturer);
        }
        return retVal;
    }

    /**
    * Inserts one DrugManufacturer into the database.  Returns the new priKey.
    */
    public static long insert(DrugManufacturer drugManufacturer) throws Exception {
        if (OpenDentBusiness.DataConnection.DBtype == OpenDentBusiness.DatabaseType.Oracle)
        {
            drugManufacturer.DrugManufacturerNum = DbHelper.getNextOracleKey("drugmanufacturer","DrugManufacturerNum");
            int loopcount = 0;
            while (loopcount < 100)
            {
                try
                {
                    return Insert(drugManufacturer, true);
                }
                catch (Oracle.DataAccess.Client.OracleException ex)
                {
                    if (ex.Number == 1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated"))
                    {
                        drugManufacturer.DrugManufacturerNum++;
                        loopcount++;
                    }
                    else
                    {
                        throw ex;
                    } 
                }
            
            }
            throw new ApplicationException("Insert failed.  Could not generate primary key.");
        }
        else
        {
            return Insert(drugManufacturer, false);
        } 
    }

    /**
    * Inserts one DrugManufacturer into the database.  Provides option to use the existing priKey.
    */
    public static long insert(DrugManufacturer drugManufacturer, boolean useExistingPK) throws Exception {
        if (!useExistingPK && PrefC.getRandomKeys())
        {
            drugManufacturer.DrugManufacturerNum = ReplicationServers.getKey("drugmanufacturer","DrugManufacturerNum");
        }
         
        String command = "INSERT INTO drugmanufacturer (";
        if (useExistingPK || PrefC.getRandomKeys())
        {
            command += "DrugManufacturerNum,";
        }
         
        command += "ManufacturerName,ManufacturerCode) VALUES(";
        if (useExistingPK || PrefC.getRandomKeys())
        {
            command += POut.long(drugManufacturer.DrugManufacturerNum) + ",";
        }
         
        command += "'" + POut.string(drugManufacturer.ManufacturerName) + "'," + "'" + POut.string(drugManufacturer.ManufacturerCode) + "')";
        if (useExistingPK || PrefC.getRandomKeys())
        {
            Db.nonQ(command);
        }
        else
        {
            drugManufacturer.DrugManufacturerNum = Db.nonQ(command,true);
        } 
        return drugManufacturer.DrugManufacturerNum;
    }

    /**
    * Updates one DrugManufacturer in the database.
    */
    public static void update(DrugManufacturer drugManufacturer) throws Exception {
        String command = "UPDATE drugmanufacturer SET " + "ManufacturerName   = '" + POut.string(drugManufacturer.ManufacturerName) + "', " + "ManufacturerCode   = '" + POut.string(drugManufacturer.ManufacturerCode) + "' " + "WHERE DrugManufacturerNum = " + POut.long(drugManufacturer.DrugManufacturerNum);
        Db.nonQ(command);
    }

    /**
    * Updates one DrugManufacturer in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.
    */
    public static void update(DrugManufacturer drugManufacturer, DrugManufacturer oldDrugManufacturer) throws Exception {
        String command = "";
        if (!StringSupport.equals(drugManufacturer.ManufacturerName, oldDrugManufacturer.ManufacturerName))
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "ManufacturerName = '" + POut.string(drugManufacturer.ManufacturerName) + "'";
        }
         
        if (!StringSupport.equals(drugManufacturer.ManufacturerCode, oldDrugManufacturer.ManufacturerCode))
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "ManufacturerCode = '" + POut.string(drugManufacturer.ManufacturerCode) + "'";
        }
         
        if (StringSupport.equals(command, ""))
        {
            return ;
        }
         
        command = "UPDATE drugmanufacturer SET " + command + " WHERE DrugManufacturerNum = " + POut.long(drugManufacturer.DrugManufacturerNum);
        Db.nonQ(command);
    }

    /**
    * Deletes one DrugManufacturer from the database.
    */
    public static void delete(long drugManufacturerNum) throws Exception {
        String command = "DELETE FROM drugmanufacturer " + "WHERE DrugManufacturerNum = " + POut.long(drugManufacturerNum);
        Db.nonQ(command);
    }

}


