//
// Translated by CS2J (http://www.cs2j.com): 2/15/2016 5:58:02 PM
//

package OpenDentBusiness.Crud;

import CS2JNet.System.StringSupport;
import OpenDentBusiness.Db;
import OpenDentBusiness.DbHelper;
import OpenDentBusiness.EhrMeasure;
import OpenDentBusiness.EhrMeasureType;
import OpenDentBusiness.PIn;
import OpenDentBusiness.POut;
import OpenDentBusiness.PrefC;
import OpenDentBusiness.RemotingClient;
import OpenDentBusiness.RemotingRole;
import OpenDentBusiness.ReplicationServers;

//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
public class EhrMeasureCrud   
{
    /**
    * Gets one EhrMeasure object from the database using the primary key.  Returns null if not found.
    */
    public static EhrMeasure selectOne(long ehrMeasureNum) throws Exception {
        String command = "SELECT * FROM ehrmeasure " + "WHERE EhrMeasureNum = " + POut.long(ehrMeasureNum);
        List<EhrMeasure> list = tableToList(Db.getTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets one EhrMeasure object from the database using a query.
    */
    public static EhrMeasure selectOne(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<EhrMeasure> list = tableToList(Db.getTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets a list of EhrMeasure objects from the database using a query.
    */
    public static List<EhrMeasure> selectMany(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<EhrMeasure> list = tableToList(Db.getTable(command));
        return list;
    }

    /**
    * Converts a DataTable to a list of objects.
    */
    public static List<EhrMeasure> tableToList(DataTable table) throws Exception {
        List<EhrMeasure> retVal = new List<EhrMeasure>();
        EhrMeasure ehrMeasure;
        for (int i = 0;i < table.Rows.Count;i++)
        {
            ehrMeasure = new EhrMeasure();
            ehrMeasure.EhrMeasureNum = PIn.Long(table.Rows[i]["EhrMeasureNum"].ToString());
            ehrMeasure.MeasureType = (EhrMeasureType)PIn.Int(table.Rows[i]["MeasureType"].ToString());
            ehrMeasure.Numerator = PIn.Int(table.Rows[i]["Numerator"].ToString());
            ehrMeasure.Denominator = PIn.Int(table.Rows[i]["Denominator"].ToString());
            retVal.Add(ehrMeasure);
        }
        return retVal;
    }

    /**
    * Inserts one EhrMeasure into the database.  Returns the new priKey.
    */
    public static long insert(EhrMeasure ehrMeasure) throws Exception {
        if (OpenDentBusiness.DataConnection.DBtype == OpenDentBusiness.DatabaseType.Oracle)
        {
            ehrMeasure.EhrMeasureNum = DbHelper.getNextOracleKey("ehrmeasure","EhrMeasureNum");
            int loopcount = 0;
            while (loopcount < 100)
            {
                try
                {
                    return Insert(ehrMeasure, true);
                }
                catch (Oracle.DataAccess.Client.OracleException ex)
                {
                    if (ex.Number == 1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated"))
                    {
                        ehrMeasure.EhrMeasureNum++;
                        loopcount++;
                    }
                    else
                    {
                        throw ex;
                    } 
                }
            
            }
            throw new ApplicationException("Insert failed.  Could not generate primary key.");
        }
        else
        {
            return Insert(ehrMeasure, false);
        } 
    }

    /**
    * Inserts one EhrMeasure into the database.  Provides option to use the existing priKey.
    */
    public static long insert(EhrMeasure ehrMeasure, boolean useExistingPK) throws Exception {
        if (!useExistingPK && PrefC.getRandomKeys())
        {
            ehrMeasure.EhrMeasureNum = ReplicationServers.getKey("ehrmeasure","EhrMeasureNum");
        }
         
        String command = "INSERT INTO ehrmeasure (";
        if (useExistingPK || PrefC.getRandomKeys())
        {
            command += "EhrMeasureNum,";
        }
         
        command += "MeasureType,Numerator,Denominator) VALUES(";
        if (useExistingPK || PrefC.getRandomKeys())
        {
            command += POut.long(ehrMeasure.EhrMeasureNum) + ",";
        }
         
        command += POut.int(((Enum)ehrMeasure.MeasureType).ordinal()) + "," + POut.int(ehrMeasure.Numerator) + "," + POut.int(ehrMeasure.Denominator) + ")";
        if (useExistingPK || PrefC.getRandomKeys())
        {
            Db.nonQ(command);
        }
        else
        {
            ehrMeasure.EhrMeasureNum = Db.nonQ(command,true);
        } 
        return ehrMeasure.EhrMeasureNum;
    }

    /**
    * Updates one EhrMeasure in the database.
    */
    public static void update(EhrMeasure ehrMeasure) throws Exception {
        String command = "UPDATE ehrmeasure SET " + "MeasureType  =  " + POut.int(((Enum)ehrMeasure.MeasureType).ordinal()) + ", " + "Numerator    =  " + POut.int(ehrMeasure.Numerator) + ", " + "Denominator  =  " + POut.int(ehrMeasure.Denominator) + " " + "WHERE EhrMeasureNum = " + POut.long(ehrMeasure.EhrMeasureNum);
        Db.nonQ(command);
    }

    /**
    * Updates one EhrMeasure in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.
    */
    public static void update(EhrMeasure ehrMeasure, EhrMeasure oldEhrMeasure) throws Exception {
        String command = "";
        if (ehrMeasure.MeasureType != oldEhrMeasure.MeasureType)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "MeasureType = " + POut.int(((Enum)ehrMeasure.MeasureType).ordinal()) + "";
        }
         
        if (ehrMeasure.Numerator != oldEhrMeasure.Numerator)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "Numerator = " + POut.int(ehrMeasure.Numerator) + "";
        }
         
        if (ehrMeasure.Denominator != oldEhrMeasure.Denominator)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "Denominator = " + POut.int(ehrMeasure.Denominator) + "";
        }
         
        if (StringSupport.equals(command, ""))
        {
            return ;
        }
         
        command = "UPDATE ehrmeasure SET " + command + " WHERE EhrMeasureNum = " + POut.long(ehrMeasure.EhrMeasureNum);
        Db.nonQ(command);
    }

    /**
    * Deletes one EhrMeasure from the database.
    */
    public static void delete(long ehrMeasureNum) throws Exception {
        String command = "DELETE FROM ehrmeasure " + "WHERE EhrMeasureNum = " + POut.long(ehrMeasureNum);
        Db.nonQ(command);
    }

}


