//
// Translated by CS2J (http://www.cs2j.com): 2/15/2016 8:01:43 PM
//

package SparksToothChart.Properties;

import SparksToothChart.Properties.Settings;


//------------------------------------------------------------------------------// <auto-generated>//     This code was generated by a tool.//     Runtime Version:4.0.30319.235////     Changes to this file may cause incorrect behavior and will be lost if//     the code is regenerated.// </auto-generated>//------------------------------------------------------------------------------
public final class Settings  extends System.Configuration.ApplicationSettingsBase 
{

    private static Settings defaultInstance = ((Settings)(/* [UNSUPPORTED] external aliases are not yet supported "global::System" */.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
    public static Settings getDefault() throws Exception {
        return defaultInstance;
    }

}


