//
// Translated by CS2J (http://www.cs2j.com): 2/15/2016 8:08:03 PM
//

package OpenDentBusiness.Crud;

import CS2JNet.System.StringSupport;

//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
public class OrionProcCrud   
{
    /**
    * Gets one OrionProc object from the database using the primary key.  Returns null if not found.
    */
    public static OrionProc selectOne(long orionProcNum) throws Exception {
        String command = "SELECT * FROM orionproc " + "WHERE OrionProcNum = " + POut.Long(orionProcNum);
        List<OrionProc> list = TableToList(Db.GetTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets one OrionProc object from the database using a query.
    */
    public static OrionProc selectOne(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<OrionProc> list = TableToList(Db.GetTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets a list of OrionProc objects from the database using a query.
    */
    public static List<OrionProc> selectMany(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<OrionProc> list = TableToList(Db.GetTable(command));
        return list;
    }

    /**
    * Converts a DataTable to a list of objects.
    */
    public static List<OrionProc> tableToList(DataTable table) throws Exception {
        List<OrionProc> retVal = new List<OrionProc>();
        OrionProc orionProc = new OrionProc();
        for (int i = 0;i < table.Rows.Count;i++)
        {
            orionProc = new OrionProc();
            orionProc.OrionProcNum = PIn.Long(table.Rows[i]["OrionProcNum"].ToString());
            orionProc.ProcNum = PIn.Long(table.Rows[i]["ProcNum"].ToString());
            orionProc.DPC = (OrionDPC)PIn.Int(table.Rows[i]["DPC"].ToString());
            orionProc.DPCpost = (OrionDPC)PIn.Int(table.Rows[i]["DPCpost"].ToString());
            orionProc.DateScheduleBy = PIn.Date(table.Rows[i]["DateScheduleBy"].ToString());
            orionProc.DateStopClock = PIn.Date(table.Rows[i]["DateStopClock"].ToString());
            orionProc.Status2 = (OrionStatus)PIn.Int(table.Rows[i]["Status2"].ToString());
            orionProc.IsOnCall = PIn.Bool(table.Rows[i]["IsOnCall"].ToString());
            orionProc.IsEffectiveComm = PIn.Bool(table.Rows[i]["IsEffectiveComm"].ToString());
            orionProc.IsRepair = PIn.Bool(table.Rows[i]["IsRepair"].ToString());
            retVal.Add(orionProc);
        }
        return retVal;
    }

    /**
    * Inserts one OrionProc into the database.  Returns the new priKey.
    */
    public static long insert(OrionProc orionProc) throws Exception {
        if (DataConnection.DBtype == DatabaseType.Oracle)
        {
            orionProc.OrionProcNum = DbHelper.GetNextOracleKey("orionproc", "OrionProcNum");
            int loopcount = 0;
            while (loopcount < 100)
            {
                try
                {
                    return insert(orionProc,true);
                }
                catch (Oracle.DataAccess.Client.OracleException ex)
                {
                    if (ex.Number == 1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated"))
                    {
                        orionProc.OrionProcNum++;
                        loopcount++;
                    }
                    else
                    {
                        throw ex;
                    } 
                }
            
            }
            throw new ApplicationException("Insert failed.  Could not generate primary key.");
        }
        else
        {
            return insert(orionProc,false);
        } 
    }

    /**
    * Inserts one OrionProc into the database.  Provides option to use the existing priKey.
    */
    public static long insert(OrionProc orionProc, boolean useExistingPK) throws Exception {
        if (!useExistingPK && PrefC.RandomKeys)
        {
            orionProc.OrionProcNum = ReplicationServers.GetKey("orionproc", "OrionProcNum");
        }
         
        String command = "INSERT INTO orionproc (";
        if (useExistingPK || PrefC.RandomKeys)
        {
            command += "OrionProcNum,";
        }
         
        command += "ProcNum,DPC,DPCpost,DateScheduleBy,DateStopClock,Status2,IsOnCall,IsEffectiveComm,IsRepair) VALUES(";
        if (useExistingPK || PrefC.RandomKeys)
        {
            command += POut.Long(orionProc.OrionProcNum) + ",";
        }
         
        command += POut.Long(orionProc.ProcNum) + "," + POut.Int((int)orionProc.DPC) + "," + POut.Int((int)orionProc.DPCpost) + "," + POut.Date(orionProc.DateScheduleBy) + "," + POut.Date(orionProc.DateStopClock) + "," + POut.Int((int)orionProc.Status2) + "," + POut.Bool(orionProc.IsOnCall) + "," + POut.Bool(orionProc.IsEffectiveComm) + "," + POut.Bool(orionProc.IsRepair) + ")";
        if (useExistingPK || PrefC.RandomKeys)
        {
            Db.NonQ(command);
        }
        else
        {
            orionProc.OrionProcNum = Db.NonQ(command, true);
        } 
        return orionProc.OrionProcNum;
    }

    /**
    * Updates one OrionProc in the database.
    */
    public static void update(OrionProc orionProc) throws Exception {
        String command = "UPDATE orionproc SET " + "ProcNum        =  " + POut.Long(orionProc.ProcNum) + ", " + "DPC            =  " + POut.Int((int)orionProc.DPC) + ", " + "DPCpost        =  " + POut.Int((int)orionProc.DPCpost) + ", " + "DateScheduleBy =  " + POut.Date(orionProc.DateScheduleBy) + ", " + "DateStopClock  =  " + POut.Date(orionProc.DateStopClock) + ", " + "Status2        =  " + POut.Int((int)orionProc.Status2) + ", " + "IsOnCall       =  " + POut.Bool(orionProc.IsOnCall) + ", " + "IsEffectiveComm=  " + POut.Bool(orionProc.IsEffectiveComm) + ", " + "IsRepair       =  " + POut.Bool(orionProc.IsRepair) + " " + "WHERE OrionProcNum = " + POut.Long(orionProc.OrionProcNum);
        Db.NonQ(command);
    }

    /**
    * Updates one OrionProc in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.
    */
    public static void update(OrionProc orionProc, OrionProc oldOrionProc) throws Exception {
        String command = "";
        if (orionProc.ProcNum != oldOrionProc.ProcNum)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "ProcNum = " + POut.Long(orionProc.ProcNum) + "";
        }
         
        if (orionProc.DPC != oldOrionProc.DPC)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "DPC = " + POut.Int((int)orionProc.DPC) + "";
        }
         
        if (orionProc.DPCpost != oldOrionProc.DPCpost)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "DPCpost = " + POut.Int((int)orionProc.DPCpost) + "";
        }
         
        if (orionProc.DateScheduleBy != oldOrionProc.DateScheduleBy)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "DateScheduleBy = " + POut.Date(orionProc.DateScheduleBy) + "";
        }
         
        if (orionProc.DateStopClock != oldOrionProc.DateStopClock)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "DateStopClock = " + POut.Date(orionProc.DateStopClock) + "";
        }
         
        if (orionProc.Status2 != oldOrionProc.Status2)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "Status2 = " + POut.Int((int)orionProc.Status2) + "";
        }
         
        if (orionProc.IsOnCall != oldOrionProc.IsOnCall)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "IsOnCall = " + POut.Bool(orionProc.IsOnCall) + "";
        }
         
        if (orionProc.IsEffectiveComm != oldOrionProc.IsEffectiveComm)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "IsEffectiveComm = " + POut.Bool(orionProc.IsEffectiveComm) + "";
        }
         
        if (orionProc.IsRepair != oldOrionProc.IsRepair)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "IsRepair = " + POut.Bool(orionProc.IsRepair) + "";
        }
         
        if (StringSupport.equals(command, ""))
        {
            return ;
        }
         
        command = "UPDATE orionproc SET " + command + " WHERE OrionProcNum = " + POut.Long(orionProc.OrionProcNum);
        Db.NonQ(command);
    }

    /**
    * Deletes one OrionProc from the database.
    */
    public static void delete(long orionProcNum) throws Exception {
        String command = "DELETE FROM orionproc " + "WHERE OrionProcNum = " + POut.Long(orionProcNum);
        Db.NonQ(command);
    }

}


