//
// Translated by CS2J (http://www.cs2j.com): 2/15/2016 8:08:07 PM
//

package OpenDentBusiness.Crud;

import CS2JNet.System.StringSupport;

//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
public class SiteCrud   
{
    /**
    * Gets one Site object from the database using the primary key.  Returns null if not found.
    */
    public static Site selectOne(long siteNum) throws Exception {
        String command = "SELECT * FROM site " + "WHERE SiteNum = " + POut.Long(siteNum);
        List<Site> list = TableToList(Db.GetTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets one Site object from the database using a query.
    */
    public static Site selectOne(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<Site> list = TableToList(Db.GetTable(command));
        if (list.Count == 0)
        {
            return null;
        }
         
        return list[0];
    }

    /**
    * Gets a list of Site objects from the database using a query.
    */
    public static List<Site> selectMany(String command) throws Exception {
        if (RemotingClient.RemotingRole == RemotingRole.ClientWeb)
        {
            throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n" + command);
        }
         
        List<Site> list = TableToList(Db.GetTable(command));
        return list;
    }

    /**
    * Converts a DataTable to a list of objects.
    */
    public static List<Site> tableToList(DataTable table) throws Exception {
        List<Site> retVal = new List<Site>();
        Site site = new Site();
        for (int i = 0;i < table.Rows.Count;i++)
        {
            site = new Site();
            site.SiteNum = PIn.Long(table.Rows[i]["SiteNum"].ToString());
            site.Description = PIn.String(table.Rows[i]["Description"].ToString());
            site.Note = PIn.String(table.Rows[i]["Note"].ToString());
            retVal.Add(site);
        }
        return retVal;
    }

    /**
    * Inserts one Site into the database.  Returns the new priKey.
    */
    public static long insert(Site site) throws Exception {
        if (DataConnection.DBtype == DatabaseType.Oracle)
        {
            site.SiteNum = DbHelper.GetNextOracleKey("site", "SiteNum");
            int loopcount = 0;
            while (loopcount < 100)
            {
                try
                {
                    return insert(site,true);
                }
                catch (Oracle.DataAccess.Client.OracleException ex)
                {
                    if (ex.Number == 1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated"))
                    {
                        site.SiteNum++;
                        loopcount++;
                    }
                    else
                    {
                        throw ex;
                    } 
                }
            
            }
            throw new ApplicationException("Insert failed.  Could not generate primary key.");
        }
        else
        {
            return insert(site,false);
        } 
    }

    /**
    * Inserts one Site into the database.  Provides option to use the existing priKey.
    */
    public static long insert(Site site, boolean useExistingPK) throws Exception {
        if (!useExistingPK && PrefC.RandomKeys)
        {
            site.SiteNum = ReplicationServers.GetKey("site", "SiteNum");
        }
         
        String command = "INSERT INTO site (";
        if (useExistingPK || PrefC.RandomKeys)
        {
            command += "SiteNum,";
        }
         
        command += "Description,Note) VALUES(";
        if (useExistingPK || PrefC.RandomKeys)
        {
            command += POut.Long(site.SiteNum) + ",";
        }
         
        command += "'" + POut.String(site.Description) + "'," + "'" + POut.String(site.Note) + "')";
        if (useExistingPK || PrefC.RandomKeys)
        {
            Db.NonQ(command);
        }
        else
        {
            site.SiteNum = Db.NonQ(command, true);
        } 
        return site.SiteNum;
    }

    /**
    * Updates one Site in the database.
    */
    public static void update(Site site) throws Exception {
        String command = "UPDATE site SET " + "Description= '" + POut.String(site.Description) + "', " + "Note       = '" + POut.String(site.Note) + "' " + "WHERE SiteNum = " + POut.Long(site.SiteNum);
        Db.NonQ(command);
    }

    /**
    * Updates one Site in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.
    */
    public static void update(Site site, Site oldSite) throws Exception {
        String command = "";
        if (site.Description != oldSite.Description)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "Description = '" + POut.String(site.Description) + "'";
        }
         
        if (site.Note != oldSite.Note)
        {
            if (!StringSupport.equals(command, ""))
            {
                command += ",";
            }
             
            command += "Note = '" + POut.String(site.Note) + "'";
        }
         
        if (StringSupport.equals(command, ""))
        {
            return ;
        }
         
        command = "UPDATE site SET " + command + " WHERE SiteNum = " + POut.Long(site.SiteNum);
        Db.NonQ(command);
    }

    /**
    * Deletes one Site from the database.
    */
    public static void delete(long siteNum) throws Exception {
        String command = "DELETE FROM site " + "WHERE SiteNum = " + POut.Long(siteNum);
        Db.NonQ(command);
    }

}


